
//Auth
export const AUTHENTICATION_AUTH = 'AUTHENTICATION_AUTH';
export const TOKEN_AUTHENTICATION_AUTH = 'TOKEN_AUTHENTICATION_AUTH';
export const USER_INFO_AUTH = 'USER_INFO_AUTH';
export const LOGIN_SUCCESS_AUTH = 'LOGIN_SUCCESS_AUTH';

//Proyecto
export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const LISTA_PROYECTOS = 'LISTA_PROYECTOS';
export const SELECCIONAR_PROYECTO = 'SELECCIONAR_PROYECTO';

//Tareas
export const LISTA_TAREAS = 'LISTA_TAREAS';
export const EDITANDO_TAREAS = 'EDITANDO_TAREAS';